version: '3.5'

services:

  next:
    build: .
    container_name: next
    restart: unless-stopped
    tty: true
    ports:
      - "3000:3000"
    environment:
      API_URL: http://webserver/jsonapi
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app 
    networks:
      - app-network

networks:
  app-network:
    name: api-network
    driver: bridge